"use client";

import { useMemo, useState } from "react";

type Evidence = { source: string; note: string; confidence: number };
type Insight = { id: string; activity: string; process: string; role: string; impact: "Automate" | "Augment" | "Redesign"; confidence: number; skill: string; rationale: string; evidence: Evidence[] };

const insights: Insight[] = [
  { id: "IT-01", activity: "Ticket classification", process: "Incident Management", role: "Service Desk Analyst", impact: "Automate", confidence: 92, skill: "Exception management", rationale: "AI can identify the incident category, affected service and likely assignment group from a ticket, while low-confidence classifications are routed to an analyst.", evidence: [{ source: "ITIL incident practice", note: "Classification and prioritisation are core incident activities", confidence: 91 }, { source: "Service desk policy", note: "Humans approve high-impact incident routing", confidence: 94 }] },
  { id: "IT-02", activity: "Knowledge article retrieval", process: "Incident Management", role: "Service Desk Analyst", impact: "Augment", confidence: 87, skill: "AI-assisted troubleshooting", rationale: "Retrieval can surface the most relevant troubleshooting articles, but the analyst validates the resolution against the user’s context.", evidence: [{ source: "Knowledge management guide", note: "Approved articles support first-contact resolution", confidence: 90 }, { source: "IT support controls", note: "Analyst validates the recommended action", confidence: 92 }] },
  { id: "IT-03", activity: "Access request review", process: "Access Management", role: "IT Support Engineer", impact: "Augment", confidence: 81, skill: "Identity-risk assessment", rationale: "AI can extract request details and check policy requirements, while the engineer retains responsibility for privileged access decisions.", evidence: [{ source: "Access control standard", note: "Privileged access needs accountable approval", confidence: 94 }] },
  { id: "IT-04", activity: "Password reset fulfilment", process: "Request Fulfilment", role: "Service Desk Analyst", impact: "Automate", confidence: 95, skill: "Automation supervision", rationale: "A verified, policy-controlled workflow can complete routine password resets and only escalate identity-verification failures.", evidence: [{ source: "Service catalogue", note: "Password reset is a repeatable standard request", confidence: 96 }] },
  { id: "IT-05", activity: "Major incident communication", process: "Major Incident Management", role: "IT Operations Manager", impact: "Redesign", confidence: 78, skill: "AI-assisted communication", rationale: "AI can synthesise technical updates and draft stakeholder communications, shifting the manager’s role toward incident command and decision-making.", evidence: [{ source: "Major incident playbook", note: "Incident commander owns business communication", confidence: 88 }] },
];
const impactColors = { Automate: "auto", Augment: "augment", Redesign: "redesign" };

export default function Home() {
  const [selected, setSelected] = useState<Insight>(insights[0]);
  const [query, setQuery] = useState("How will AI affect Service Desk Analysts?");
  const [submitted, setSubmitted] = useState(false);
  const [filter, setFilter] = useState("All impact types");
  const filtered = useMemo(() => filter === "All impact types" ? insights : insights.filter((item) => item.impact === filter), [filter]);
  return <main>
    <aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><span>modus<span className="brand-ai">AI</span></span></div><div className="workspace"><span className="status-dot" /> IT service intelligence</div><nav><a className="nav-link active" href="#overview"><span>◈</span> Overview</a><a className="nav-link" href="#graph"><span>⌘</span> Intelligence graph</a><a className="nav-link" href="#impact"><span>✦</span> AI impact assessment</a><a className="nav-link" href="#evidence"><span>▤</span> Evidence library</a></nav><div className="sidebar-bottom"><div className="mini-user"><div className="avatar">AS</div><div><strong>Alex Singh</strong><small>Transformation team</small></div><span>⌄</span></div></div></aside>
    <section className="app-shell"><header className="topbar"><div className="crumb"><span>Enterprise intelligence</span><b>/</b><strong>IT service operating model</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications">◌</button><button className="icon-button" aria-label="Settings">⚙</button><button className="avatar">AS</button></div></header>
      <div className="content"><section className="hero" id="overview"><div><p className="eyebrow">PROCESS × ROLE × SKILL INTELLIGENCE</p><h1>Make every AI decision<br /><em>explainable.</em></h1><p className="hero-copy">Trace how AI changes IT support work—from ticket and service process to people, skills and accountable decisions.</p></div><div className="health-card"><div className="health-head"><span>OPERATING MODEL HEALTH</span><span className="live"><i /> LIVE</span></div><div className="health-score">81<span>/100</span></div><div className="health-bar"><i /></div><p>Ready to scale, with 6 activities requiring targeted role transition plans.</p></div></section>
        <section className="metrics"><Metric number="12" label="Mapped processes" delta="+2 this month" /><Metric number="46" label="Connected activities" delta="6 AI-ready" /><Metric number="9" label="Roles in scope" delta="3 changing materially" /><Metric number="18" label="Future skills" delta="4 critical gaps" /></section>
        <section className="ask-card"><div className="ask-title"><span className="spark">✦</span><div><strong>Ask your operating model</strong><p>Answers are grounded in connected ticket, process, role and skill evidence.</p></div></div><div className="ask-input"><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Ask a question" /><button onClick={() => setSubmitted(true)}>Generate insight <span>→</span></button></div>{submitted && <div className="answer"><span>✦</span><p><b>Service Desk Analysts shift from manual ticket routing to judgment-led incident resolution.</b> AI automates classification and routine fulfilment, while creating a priority skill need in AI-assisted troubleshooting and exception management. <a href="#impact">View evidence →</a></p></div>}</section>
        <TicketIntake />
        <section className="section-head" id="graph"><div><p className="eyebrow">CONNECTED INTELLIGENCE</p><h2>Role impact map</h2></div><button className="text-button">Explore full graph <span>→</span></button></section><section className="graph-card"><div className="graph-legend"><span><i className="dot navy" /> Process</span><span><i className="dot teal" /> Activity</span><span><i className="dot amber" /> Role</span><span><i className="dot purple" /> Skill</span></div><div className="graph-stage"><div className="line l1" /><div className="line l2" /><div className="line l3" /><div className="line l4" /><GraphNode className="n1 process" label="Incident Management" sub="PROCESS" /><GraphNode className="n2 activity" label="Ticket classification" sub="ACTIVITY" /><GraphNode className="n3 role" label="Service Desk Analyst" sub="ROLE" selected /><GraphNode className="n4 skill" label="Exception management" sub="FUTURE SKILL" /><GraphNode className="n5 activity" label="Knowledge retrieval" sub="ACTIVITY" /><GraphNode className="n6 role" label="IT Support Engineer" sub="ROLE" /><GraphNode className="n7 skill" label="AI troubleshooting" sub="FUTURE SKILL" /></div><div className="graph-footer"><span><b>3 processes</b> connect to Service Desk Analyst</span><span><b>8 activities</b> are affected by AI</span><span><b>5 skills</b> are changing</span></div></section>
        <section className="section-head" id="impact"><div><p className="eyebrow">AI IMPACT ASSESSMENT</p><h2>Activities needing a decision</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter impacts"><option>All impact types</option><option>Automate</option><option>Augment</option><option>Redesign</option></select></section><section className="impact-grid"><div className="impact-list">{filtered.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`impact-row ${selected.id === item.id ? "selected" : ""}`}><div className={`impact-icon ${impactColors[item.impact]}`}>{item.impact === "Automate" ? "↻" : item.impact === "Augment" ? "✦" : "↗"}</div><div className="impact-main"><strong>{item.activity}</strong><span>{item.process} · {item.role}</span></div><div className="confidence"><span>{item.confidence}%</span><small>confidence</small></div><i className={`pill ${impactColors[item.impact]}`}>{item.impact}</i></button>)}</div><article className="detail-card" id="evidence"><div className="detail-top"><span className={`pill ${impactColors[selected.impact]}`}>{selected.impact}</span><span className="record-id">{selected.id}</span></div><h3>{selected.activity}</h3><p className="detail-meta">{selected.process} <b>→</b> {selected.role}</p><p className="rationale">{selected.rationale}</p><div className="skill-callout"><span>↗</span><div><small>FUTURE-CRITICAL SKILL</small><strong>{selected.skill}</strong></div></div><div className="evidence-title"><span>Grounding evidence</span><small>{selected.evidence.length} sources</small></div>{selected.evidence.map((evidence) => <div className="evidence" key={evidence.source}><span>▤</span><div><strong>{evidence.source}</strong><p>{evidence.note}</p></div><b>{evidence.confidence}%</b></div>)}<button className="detail-link">Open relationship trail <span>→</span></button></article></section></div></section>
  </main>;
}
function Metric({ number, label, delta }: { number: string; label: string; delta: string }) { return <div className="metric"><strong>{number}</strong><span>{label}</span><small><i /> {delta}</small></div>; }
function GraphNode({ label, sub, className, selected = false }: { label: string; sub: string; className: string; selected?: boolean }) { return <div className={`graph-node ${className} ${selected ? "node-selected" : ""}`}><span>{sub}</span><strong>{label}</strong></div>; }
function TicketIntake() {
  const [ticket, setTicket] = useState({ title: "", service: "", description: "" });
  const [error, setError] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [result, setResult] = useState<{ category: string; assignmentGroup: string; confidence: number; recommendation: string; escalationRequired: boolean } | null>(null);
  const validate = () => {
    if (!ticket.title.trim() || !ticket.service || !ticket.description.trim()) { setError("Add a title, service, and description before analysing the ticket."); return false; }
    setError(""); return true;
  };
  const submit = async () => {
    if (!validate()) return;
    setIsSubmitting(true); setResult(null);
    try {
      const response = await fetch("/api/tickets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...ticket, requester: "demo.user@example.com", priority: "P3" }) });
      const data = await response.json() as { error?: string; assessment?: { category: string; assignmentGroup: string; confidence: number; recommendation: string; escalationRequired: boolean } };
      if (!response.ok || !data.assessment) throw new Error(data.error ?? "Unable to analyse this ticket.");
      setResult(data.assessment);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to analyse this ticket."); }
    finally { setIsSubmitting(false); }
  };
  return <section className="ticket-intake" id="new-ticket"><div><p className="eyebrow">LIVE TICKET INTAKE</p><h2>Analyse a new service request</h2><p>Enter a ticket to classify it, retrieve relevant knowledge, and recommend the right route.</p></div><form><label>Ticket title<input value={ticket.title} onChange={(event) => setTicket({ ...ticket, title: event.target.value })} placeholder="e.g. VPN disconnects after sign-in" /></label><label>Service<select value={ticket.service} onChange={(event) => setTicket({ ...ticket, service: event.target.value })}><option value="" disabled>Select service</option><option>Identity</option><option>Network</option><option>Collaboration</option><option>Workplace</option></select></label><label className="ticket-wide">Description<textarea value={ticket.description} onChange={(event) => setTicket({ ...ticket, description: event.target.value })} placeholder="Describe what happened, who is affected, and any error message." /></label>{error && <p className="ticket-error" role="alert">{error}</p>}{result && <TicketResult result={result} />}<button type="button" onClick={submit} disabled={isSubmitting}>{isSubmitting ? "Analysing…" : "Analyse ticket"} <span>→</span></button></form></section>;
}
function TicketResult({ result }: { result: { category: string; assignmentGroup: string; confidence: number; recommendation: string; escalationRequired: boolean } }) { return <div className="ticket-result"><span>AI assessment</span><strong>{result.category} · {result.confidence}% confidence</strong><p>{result.recommendation}</p><small>{result.escalationRequired ? "Escalation required" : `Route to ${result.assignmentGroup}`}</small></div>; }
