"use client";

import { useMemo, useState } from "react";

type Evidence = { source: string; note: string; confidence: number };
type Insight = { id: string; activity: string; process: string; role: string; impact: "Automate" | "Augment" | "Redesign"; confidence: number; skill: string; rationale: string; evidence: Evidence[] };

const insights: Insight[] = [
  { id: "AP-01", activity: "Supplier shortlisting", process: "Source-to-Contract", role: "Procurement Analyst", impact: "Augment", confidence: 86, skill: "AI-assisted research", rationale: "AI can consolidate supplier signals and draft a ranked longlist; the analyst validates fit, risk and commercial context.", evidence: [{ source: "Procurement Operating Model v1.2", note: "Analyst owns supplier discovery", confidence: 94 }, { source: "Internal AI controls", note: "Human approval required for supplier decisions", confidence: 92 }] },
  { id: "AP-02", activity: "Bid comparison", process: "Source-to-Contract", role: "Procurement Analyst", impact: "Automate", confidence: 91, skill: "Exception management", rationale: "Structured bids can be normalized and scored automatically, with exceptions routed to the buyer.", evidence: [{ source: "RFP template library", note: "Comparable commercial fields", confidence: 89 }, { source: "AI controls", note: "Transparent scoring required", confidence: 91 }] },
  { id: "AP-03", activity: "Contract clause review", process: "Source-to-Contract", role: "Category Manager", impact: "Augment", confidence: 82, skill: "Negotiation strategy", rationale: "Clause deviations can be highlighted against playbooks while the category manager retains negotiation accountability.", evidence: [{ source: "Legal playbook", note: "Fallback clauses are standardised", confidence: 84 }] },
  { id: "AP-04", activity: "PO exception triage", process: "Procure-to-Pay", role: "Procurement Operations Lead", impact: "Automate", confidence: 88, skill: "Workflow supervision", rationale: "Policy-based triage is repeatable; only low-confidence or high-value exceptions need human review.", evidence: [{ source: "P2P exception report", note: "Most cases are policy-matchable", confidence: 87 }] },
  { id: "AP-05", activity: "Supplier performance review", process: "Supplier Management", role: "Category Manager", impact: "Redesign", confidence: 76, skill: "Data storytelling", rationale: "AI can synthesize delivery, quality and risk signals, shifting the role toward joint performance interventions.", evidence: [{ source: "Supplier scorecard", note: "Monthly review cadence", confidence: 78 }] },
];
const impactColors = { Automate: "auto", Augment: "augment", Redesign: "redesign" };

export default function Home() {
  const [selected, setSelected] = useState<Insight>(insights[0]);
  const [query, setQuery] = useState("How will AI affect Procurement Analysts?");
  const [submitted, setSubmitted] = useState(false);
  const [filter, setFilter] = useState("All impact types");
  const filtered = useMemo(() => filter === "All impact types" ? insights : insights.filter((item) => item.impact === filter), [filter]);
  return <main>
    <aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><span>modus<span className="brand-ai">AI</span></span></div><div className="workspace"><span className="status-dot" /> Procurement intelligence</div><nav><a className="nav-link active" href="#overview"><span>◈</span> Overview</a><a className="nav-link" href="#graph"><span>⌘</span> Intelligence graph</a><a className="nav-link" href="#impact"><span>✦</span> AI impact assessment</a><a className="nav-link" href="#evidence"><span>▤</span> Evidence library</a></nav><div className="sidebar-bottom"><div className="mini-user"><div className="avatar">AS</div><div><strong>Alex Singh</strong><small>Transformation team</small></div><span>⌄</span></div></div></aside>
    <section className="app-shell"><header className="topbar"><div className="crumb"><span>Enterprise intelligence</span><b>/</b><strong>Procurement operating model</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications">◌</button><button className="icon-button" aria-label="Settings">⚙</button><button className="avatar">AS</button></div></header>
      <div className="content"><section className="hero" id="overview"><div><p className="eyebrow">PROCESS × ROLE × SKILL INTELLIGENCE</p><h1>Make every AI decision<br /><em>explainable.</em></h1><p className="hero-copy">Trace how AI changes work across your procurement operating model—from process and activity to people, skills and accountable decisions.</p></div><div className="health-card"><div className="health-head"><span>OPERATING MODEL HEALTH</span><span className="live"><i /> LIVE</span></div><div className="health-score">78<span>/100</span></div><div className="health-bar"><i /></div><p>Ready to scale, with 8 activities requiring targeted role transition plans.</p></div></section>
        <section className="metrics"><Metric number="12" label="Mapped processes" delta="+2 this month" /><Metric number="46" label="Connected activities" delta="6 AI-ready" /><Metric number="9" label="Roles in scope" delta="3 changing materially" /><Metric number="18" label="Future skills" delta="4 critical gaps" /></section>
        <section className="ask-card"><div className="ask-title"><span className="spark">✦</span><div><strong>Ask your operating model</strong><p>Answers are grounded in your connected process, role and skill evidence.</p></div></div><div className="ask-input"><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Ask a question" /><button onClick={() => setSubmitted(true)}>Generate insight <span>→</span></button></div>{submitted && <div className="answer"><span>✦</span><p><b>Procurement Analysts shift from information gathering to judgment-led supplier evaluation.</b> AI augments supplier discovery and automates bid normalisation, creating a priority skill need in AI-assisted research and exception management. <a href="#impact">View evidence →</a></p></div>}</section>
        <section className="section-head" id="graph"><div><p className="eyebrow">CONNECTED INTELLIGENCE</p><h2>Role impact map</h2></div><button className="text-button">Explore full graph <span>→</span></button></section><section className="graph-card"><div className="graph-legend"><span><i className="dot navy" /> Process</span><span><i className="dot teal" /> Activity</span><span><i className="dot amber" /> Role</span><span><i className="dot purple" /> Skill</span></div><div className="graph-stage"><div className="line l1" /><div className="line l2" /><div className="line l3" /><div className="line l4" /><GraphNode className="n1 process" label="Source-to-Contract" sub="PROCESS" /><GraphNode className="n2 activity" label="Bid comparison" sub="ACTIVITY" /><GraphNode className="n3 role" label="Procurement Analyst" sub="ROLE" selected /><GraphNode className="n4 skill" label="Exception management" sub="FUTURE SKILL" /><GraphNode className="n5 activity" label="Supplier shortlisting" sub="ACTIVITY" /><GraphNode className="n6 role" label="Category Manager" sub="ROLE" /><GraphNode className="n7 skill" label="AI-assisted research" sub="FUTURE SKILL" /></div><div className="graph-footer"><span><b>2 processes</b> connect to Procurement Analyst</span><span><b>7 activities</b> are affected by AI</span><span><b>4 skills</b> are changing</span></div></section>
        <section className="section-head" id="impact"><div><p className="eyebrow">AI IMPACT ASSESSMENT</p><h2>Activities needing a decision</h2></div><select value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter impacts"><option>All impact types</option><option>Automate</option><option>Augment</option><option>Redesign</option></select></section><section className="impact-grid"><div className="impact-list">{filtered.map((item) => <button key={item.id} onClick={() => setSelected(item)} className={`impact-row ${selected.id === item.id ? "selected" : ""}`}><div className={`impact-icon ${impactColors[item.impact]}`}>{item.impact === "Automate" ? "↻" : item.impact === "Augment" ? "✦" : "↗"}</div><div className="impact-main"><strong>{item.activity}</strong><span>{item.process} · {item.role}</span></div><div className="confidence"><span>{item.confidence}%</span><small>confidence</small></div><i className={`pill ${impactColors[item.impact]}`}>{item.impact}</i></button>)}</div><article className="detail-card" id="evidence"><div className="detail-top"><span className={`pill ${impactColors[selected.impact]}`}>{selected.impact}</span><span className="record-id">{selected.id}</span></div><h3>{selected.activity}</h3><p className="detail-meta">{selected.process} <b>→</b> {selected.role}</p><p className="rationale">{selected.rationale}</p><div className="skill-callout"><span>↗</span><div><small>FUTURE-CRITICAL SKILL</small><strong>{selected.skill}</strong></div></div><div className="evidence-title"><span>Grounding evidence</span><small>{selected.evidence.length} sources</small></div>{selected.evidence.map((evidence) => <div className="evidence" key={evidence.source}><span>▤</span><div><strong>{evidence.source}</strong><p>{evidence.note}</p></div><b>{evidence.confidence}%</b></div>)}<button className="detail-link">Open relationship trail <span>→</span></button></article></section></div></section>
  </main>;
}
function Metric({ number, label, delta }: { number: string; label: string; delta: string }) { return <div className="metric"><strong>{number}</strong><span>{label}</span><small><i /> {delta}</small></div>; }
function GraphNode({ label, sub, className, selected = false }: { label: string; sub: string; className: string; selected?: boolean }) { return <div className={`graph-node ${className} ${selected ? "node-selected" : ""}`}><span>{sub}</span><strong>{label}</strong></div>; }
